version: '3'
services:
  front-end:
    image: "diffs/ucl-waterbeats:front-end_1.1.0"
    container_name: waterbeats-front-end
    environment:
      VUE_APP_SERVICE_URL: <Authentication_Gateway_service_URL>
    ports:
      - "8080:80"