name: Data Management Test

on: [push, pull_request]

jobs:
  test_data_management:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./DataManagement
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v3
      - name: Setup InfluxDB
        uses: influxdata/influxdb-action@v3
        with:
          influxdb_version: latest
          influxdb_org: WaterBeats
          influxdb_user: WaterBeats
          influxdb_password: WaterBeats
          influxdb_bucket: WaterBeats
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Test with pytest
        run: |
          pytest