name: Data Backend Test
on: [push, pull_request]

jobs:
  test_data_backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Setup InfluxDB
        working-directory: TSDB
        run: |
          bash ./influxdb.sh &
          sleep 10
      - name: Initialize database
        working-directory: TSDB
        run: |
          INFLUXDB_TOKEN=$(python ./create_token.py | tail -n 1) python init_data.py
      - name: Cache Cargo
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Run tests
        working-directory: DataBackend
        run: |
          export INFLUXDB_TOKEN=$(python ../TSDB/create_token.py | tail -n 1)
          cargo test
