name: Data Management Test

on: [push, pull_request]

jobs:
  test_data_management:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.10"]
    steps:
      - uses: actions/checkout@v3
      - name: Setup InfluxDB
        working-directory: TSDB
        run: |
          bash ./influxdb.sh & sleep 10
      - name: Initialize InfluxDB
        working-directory: TSDB
        run: |
          INFLUXDB_TOKEN=$(python ./create_token.py | tail -n 1)
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        working-directory: DataManagement
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Test with pytest
        working-directory: DataManagement
        run: |
          pytest