name: Edge Data Processor Test

on: [push, pull_request]

jobs:
  test_edp:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        working-directory: ./Edge_data_processor
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Start Data Buffer
        working-directory: ./DataBuffer
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi \
           && python api.py &
      - name: Test with pytest
        working-directory: ./Edge_data_processor
        run: |
          pytest