name: Front-end application CI Pipeline.

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"

      - name: Install dependencies.
        run: npm install
        working-directory: "./front-end"
      
      - name: Build the appplication.
        run: npm run build --if-present
        working-directory: "./front-end"
        
      - name: Unit test.
        run: npm test:unit --if-present
        working-directory: "./front-end"
      
      - name: E2E test.
        run: npm test:e2e --if-present
        working-directory: "./front-end"
