name: Instruction Dispatcher Service CI Pipeline.

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"

      - name: Install dependencies.
        run: npm install
        working-directory: "./InstructionDispatcher"
      
      - name: Build the appplication.
        run: npm run build --if-present
        working-directory: "./InstructionDispatcher"
        
      - name: Test the appplication.
        run: npm test
        working-directory: "./InstructionDispatcher"
